### ISSUE TITLE
assert の削除

### ISSUE THREAD

**Issue by ocha98** [ocha98/ac-library-java#17]
assert はデフォルトでは機能しないので throw に書き換えないと意味がなさそう

ライブラリの多くの各箇所で使われるので internalUtilとかつくってもよさそう

**Comment by viral8code** [comment]
assert で null チェックを行なってコンパイル時の警告を回避している、みたいなところ以外は throw で置き換えても良さそうですね
もしくは checkIndex や checkObject のようなメソッドを作っても良いかもしれません(標準ライブラリでもよく見る技法なので)

**Comment by ocha98** [comment]
なるほど。その方針で進めたいと思います
