### ISSUE TITLE
ArrayUtils

### ISSUE THREAD

**Issue by ocha98** [ocha98/ac-library-java#24]
int[], long[] 等に対する

- lowerBound
- upperBound
- dedup

があってもよさそう

**Comment by viral8code** [comment]
* lowerBound
* upperBound

上記の二つは ```java.util.Arrays::binarySearch``` が存在しますがそれをより使いやすくする、という感じですかね？

dedup は ```java.util.stream.IntStream::distinct``` ```java.util.stream.LongStream::distinct``` で出来なくはないですが、より簡潔に書けそうなので面白いと思います！

**Comment by ocha98** [comment]
そんな感じです！

`java.util.Arrays::binarySerch`は比較関数を渡さないといけないのでそれをなくして使いやすくする感じです。

`int lowerBount(int[] a, int x)`みたいな感じで呼び出せるようになるとよさそうと思ってます。


dedupは隣接重複削除でC++の`std::unique`やRustの`Vec::dedup`に相当する物を想定してます。

`int[] dedup(int[] a)`みたいな感じで呼び出せるとよさそうと思ってます。
