### ISSUE TITLE
AtCoder等で使えるようにする

### ISSUE THREAD

**Issue by ocha98** [ocha98/ac-library-java#26]
jarにして埋め込んだところ上手く動きそう

expanderを作るよりは楽そう

https://atcoder.jp/contests/abc340/submissions/50321156

ファイルがでかい

**Comment by viral8code** [comment]
何も確認できてないんですが、 ACL にあるであろうクラスを使ってコンパイル通りますかね…？

**Comment by ocha98** [comment]
今のところ問題なく動かせました！
