### ISSUE TITLE
クラスの統合

### ISSUE THREAD

**Issue by viral8code** [ocha98/ac-library-java#35]
GraphBuilder クラスと ArticulationPoint クラスと Bridge クラスは static メソッドしか保持してないこと、 GraphBuilder クラス以外のクラスのメソッドの引数の制約が GraphBuilder に依存していることから、全てをひとまとめにして GraphUtil クラスとして扱うか、 GraphBuilder で生成される隣接リストをインスタンス変数に持つ Graph クラスみたいなものを作った方が良いかも？

**Comment by ocha98** [comment]
確かにそうですね。

せっかく作り替えるならばSCC、LCAのようにコンストラクタで頂点数、addEdgeで辺追加のように呼び出し方法を揃えるとより良くなると思ってます。どうでしょうか？

**Comment by viral8code** [comment]
なるほど
それ良さそうですね
草案的なのを作ってみます

**Comment by viral8code** [comment]
相談なのですが、 `makeGraphWithInfo` のみにしてしまっても大丈夫ですかね？
`makeGraph` と `makeGraphWithInfo` のものを同時に作っても良いんですが、さほど利点が無さそうな気がしまして…
