### ISSUE TITLE
エラトステネスの篩

### ISSUE THREAD

**Issue by ocha98** [ocha98/ac-library-java#43]
エラトステネスの篩を追加するのはどうでしょうか？

コンストラクタ：`Eratosthenes(int n)`

メソッド：`getPrimes`、素数判定 `isPrime`、約数列挙 `divisors`、素因数分解 `factorize`

**Comment by viral8code** [comment]
いいですね
素数判定以降は static メソッドで一般の $N$ に対応させる感じですか？

**Comment by ocha98** [comment]
staticで行う上手い方法が思いつかなかったです。

とりあえず現状を draft pr で出しておきます。
