### ISSUE TITLE
class に final を付ける方がよいのかどうか

### ISSUE THREAD

**Issue by ocha98** [ocha98/ac-library-java#45]
基本的に現状のライブラリは継承されることは想定してないので final class に統一しても良いと考えています。

final class だと最適化が効きやすいらしいとか？（未検証）

**Comment by viral8code** [comment]
そうですね
継承されるかもしれないと判断して最適化が効かない場合もあると思うので、 final 修飾子を全クラスに付けても良いと思います

**Comment by ocha98** [comment]
finalを付ける方針にします。

**Comment by viral8code** [comment]
引数はどうしますか？
class に付けたときもそうで、目に見えて高速化するわけではないんですけれども、変数への想定外な代入を防ぐことに繋がるのと、「この変数は変化しないよ」という意図が伝わりやすいという利点があります。
もちろん無理に付ける必要はないので未統一でも良いと思いますが。

**Comment by ocha98** [comment]
今のところ引数のfinalは未統一でよいと考えています。

**Comment by viral8code** [comment]
了解です！
